/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Acer
 */
public class aboutcafe extends javax.swing.JFrame {

    
    public aboutcafe() {
        initComponents();
         this.setResizable(false);
            setLocationRelativeTo(null);
  setSize(1011,618);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        abtTxt = new javax.swing.JTextArea();
        Exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(111, 99, 99));
        jPanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/openn.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(320, 290, 380, 300);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(219, 197, 184));
        jLabel14.setText("2025");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(500, 230, 130, 44);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel8.setText("Cafe ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(500, 190, 390, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ABoutcafe.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(582, 0, 440, 620);

        jLabel2.setBackground(new java.awt.Color(111, 99, 99));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CafeCraft");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 20, 350, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to, ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 151, 32);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bahnschrift", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText(" your cozy corner of comfort and creativity! ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 386, 23);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 202, 187));
        jLabel5.setText("Cafecraft");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 100, 119, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-star-48.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 170, 53, 48);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-star-48.png"))); // NOI18N
        jLabel10.setText("jLabel6");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 170, 53, 48);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-star-48.png"))); // NOI18N
        jLabel11.setText("jLabel6");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(180, 170, 53, 48);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-star-48.png"))); // NOI18N
        jLabel12.setText("jLabel6");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(130, 170, 53, 48);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(219, 197, 184));
        jLabel13.setText("one sip at a time");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(390, 60, 160, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-kawaii-coffee-96.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 0, 90, 96);

        abtTxt.setEditable(false);
        abtTxt.setBackground(new java.awt.Color(111, 99, 99));
        abtTxt.setColumns(20);
        abtTxt.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        abtTxt.setForeground(new java.awt.Color(255, 255, 255));
        abtTxt.setLineWrap(true);
        abtTxt.setRows(5);
        abtTxt.setText("We’re more than just a café — we’re a haven\nwhere rich aromas, handcrafted drinks, and\nheartfelt conversations come together.\nWhether you’re here for your daily caffeine \nfix,a sweet treat, or just a quiet space to\nunwind, our welcoming ambiance and\npassionate team are always ready to serve\nyou with a smile. From our freshly brewed\ncoffee to our artisan-inspired menu, every\ndetail is designed to make you feel right at \nhome. So come in, grab a seat, and let the\nflavor and warmth of CaféCraft stir your soul — one sip at a time.\n\n");
        jScrollPane1.setViewportView(abtTxt);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 417, 260);

        Exitbtn.setBackground(new java.awt.Color(255, 51, 51));
        Exitbtn.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Exitbtn.setText("Exit");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Exitbtn);
        Exitbtn.setBounds(150, 500, 98, 47);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutcafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutcafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutcafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutcafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutcafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exitbtn;
    private javax.swing.JTextArea abtTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public void Exitbtnlistener(ActionListener listener){
    Exitbtn.addActionListener(listener);
}
}

