/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;



/**
 *
 * @author ASUS
 */
public class adddialouge extends javax.swing.JDialog {
    /**
     * Creates new form adddialouge
     * @param parent
     * @param modal
     */
    public adddialouge(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setSize(400,400);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemnamelabel = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        categorylabel = new javax.swing.JLabel();
        itemfield = new javax.swing.JTextField();
        pricefield = new javax.swing.JTextField();
        chooseimagebutton = new javax.swing.JButton();
        Savebutton = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        chooseimagepreview = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(189, 171, 171));
        getContentPane().setLayout(null);

        itemnamelabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        itemnamelabel.setText("Item name");
        getContentPane().add(itemnamelabel);
        itemnamelabel.setBounds(47, 66, 106, 18);

        pricelabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        pricelabel.setText("price ");
        getContentPane().add(pricelabel);
        pricelabel.setBounds(47, 107, 106, 18);

        categorylabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        categorylabel.setText("Category");
        getContentPane().add(categorylabel);
        categorylabel.setBounds(47, 151, 106, 18);

        itemfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemfieldActionPerformed(evt);
            }
        });
        getContentPane().add(itemfield);
        itemfield.setBounds(171, 59, 147, 28);

        pricefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricefieldActionPerformed(evt);
            }
        });
        getContentPane().add(pricefield);
        pricefield.setBounds(171, 99, 147, 30);

        chooseimagebutton.setBackground(new java.awt.Color(153, 255, 0));
        chooseimagebutton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        chooseimagebutton.setText("choose Image");
        chooseimagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseimagebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(chooseimagebutton);
        chooseimagebutton.setBounds(210, 204, 120, 22);

        Savebutton.setBackground(new java.awt.Color(51, 204, 0));
        Savebutton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Savebutton.setForeground(new java.awt.Color(255, 255, 255));
        Savebutton.setText("ADD");
        Savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Savebutton);
        Savebutton.setBounds(47, 256, 82, 30);

        cancel.setBackground(new java.awt.Color(255, 0, 51));
        cancel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(229, 256, 100, 30);

        chooseimagepreview.setText("choose an image");
        getContentPane().add(chooseimagepreview);
        chooseimagepreview.setBounds(76, 187, 98, 51);

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baked items", "Cold drinks", "Hot drinks" }));
        getContentPane().add(category);
        category.setBounds(170, 140, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemfieldActionPerformed

    private void chooseimagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseimagebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseimagebuttonActionPerformed

    private void SavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavebuttonActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void pricefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddialouge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddialouge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddialouge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddialouge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                adddialouge dialog = new adddialouge(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Savebutton;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JLabel categorylabel;
    private javax.swing.JButton chooseimagebutton;
    private javax.swing.JLabel chooseimagepreview;
    private javax.swing.JTextField itemfield;
    private javax.swing.JLabel itemnamelabel;
    private javax.swing.JTextField pricefield;
    private javax.swing.JLabel pricelabel;
    // End of variables declaration//GEN-END:variables

 
    public void addSaveitembuttonlistener(ActionListener listener){
        Savebutton.addActionListener(listener);
    }
    public javax.swing.JTextField getitemField(){
return itemfield;
}
        public javax.swing.JTextField getpricefield(){
return pricefield;
}
            public JComboBox<String> getcategoryfield(){
return category;
            }
            
 public void addChooseimagelistener(ActionListener listener){
        chooseimagebutton.addActionListener(listener);
    }
public void setImagePreview(Image image) {
    if (image != null) {
        ImageIcon icon = new ImageIcon(image.getScaledInstance(40, 40, Image.SCALE_SMOOTH));
        chooseimagepreview.setIcon(icon);
        chooseimagepreview.setText(""); // Clear any placeholder text
    } else {
        chooseimagepreview.setIcon(null);
        chooseimagepreview.setText("No Image Selected");
    }
}

}

