/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Acer
 */
public class admin_sidebar extends javax.swing.JFrame {

    /**
     * Creates new form admin_sidebar
     */
    public admin_sidebar() {
        initComponents();
 this.setResizable(false);
            this.setLocationRelativeTo(null);
            this.setSize(1011,618);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logoutbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnreservation = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        editmenubtn = new javax.swing.JButton();
        Viewfeedbackbtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Manageemployee = new javax.swing.JButton();
        Vieworders = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setResizable(false);
        setSize(new java.awt.Dimension(290, 260));

        Logoutbtn.setBackground(new java.awt.Color(255, 51, 51));
        Logoutbtn.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn.setText("Logout");
        Logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jButton1.setText("CafeCraft");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnreservation.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnreservation.setForeground(new java.awt.Color(51, 0, 51));
        btnreservation.setText("View Reservations");
        btnreservation.setBorder(null);
        btnreservation.setBorderPainted(false);
        btnreservation.setContentAreaFilled(false);
        btnreservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreservationActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 0));
        jButton4.setText("Home");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        editmenubtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        editmenubtn.setForeground(new java.awt.Color(51, 51, 0));
        editmenubtn.setText("Edit Menu");
        editmenubtn.setBorder(null);
        editmenubtn.setBorderPainted(false);
        editmenubtn.setContentAreaFilled(false);
        editmenubtn.setOpaque(true);
        editmenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editmenubtnActionPerformed(evt);
            }
        });

        Viewfeedbackbtn.setBackground(new java.awt.Color(51, 0, 51));
        Viewfeedbackbtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Viewfeedbackbtn.setForeground(new java.awt.Color(51, 51, 0));
        Viewfeedbackbtn.setText("View feedback");
        Viewfeedbackbtn.setBorder(null);
        Viewfeedbackbtn.setBorderPainted(false);
        Viewfeedbackbtn.setContentAreaFilled(false);
        Viewfeedbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewfeedbackbtnActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 0, 51));
        jButton7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Attendance");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        Manageemployee.setBackground(new java.awt.Color(51, 0, 51));
        Manageemployee.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Manageemployee.setForeground(new java.awt.Color(51, 51, 0));
        Manageemployee.setText("Manage employee");
        Manageemployee.setBorder(null);
        Manageemployee.setBorderPainted(false);
        Manageemployee.setContentAreaFilled(false);
        Manageemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageemployeeActionPerformed(evt);
            }
        });

        Vieworders.setBackground(new java.awt.Color(51, 0, 51));
        Vieworders.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Vieworders.setForeground(new java.awt.Color(51, 51, 0));
        Vieworders.setText("View orders");
        Vieworders.setBorder(null);
        Vieworders.setBorderPainted(false);
        Vieworders.setContentAreaFilled(false);
        Vieworders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewordersActionPerformed(evt);
            }
        });

        inventoryButton.setBackground(new java.awt.Color(51, 0, 51));
        inventoryButton.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        inventoryButton.setForeground(new java.awt.Color(51, 51, 0));
        inventoryButton.setText("Inventory");
        inventoryButton.setBorder(null);
        inventoryButton.setBorderPainted(false);
        inventoryButton.setContentAreaFilled(false);
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/width_800.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(editmenubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Manageemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Viewfeedbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Vieworders, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(editmenubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnreservation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Manageemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Viewfeedbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(Logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(Vieworders, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnreservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnreservationActionPerformed

    private void ViewfeedbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewfeedbackbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewfeedbackbtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void ManageemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageemployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageemployeeActionPerformed

    private void ViewordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewordersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewordersActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void editmenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editmenubtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editmenubtnActionPerformed

    private void LogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_sidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_sidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_sidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_sidebar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_sidebar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logoutbtn;
    private javax.swing.JButton Manageemployee;
    private javax.swing.JButton Viewfeedbackbtn;
    private javax.swing.JButton Vieworders;
    private javax.swing.JButton btnreservation;
    private javax.swing.JButton editmenubtn;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
public void addADDeditmenulistener(ActionListener listener){
    editmenubtn.addActionListener(listener);
}

public void addADDmanageemployeelistener(ActionListener listener){
    Manageemployee.addActionListener(listener);
}
public void Addlogoutlistener(ActionListener listener){
    Logoutbtn.addActionListener(listener);
}

public void Addfeedbacklistener(ActionListener listener){
    Viewfeedbackbtn.addActionListener(listener);
}
public void addReservationAdminListener(ActionListener listener) {
    btnreservation.addActionListener(listener);
}
public void addviewordersListener(ActionListener listener) {
    Vieworders.addActionListener(listener);
}

public JButton getInventoryButton() {    
    return inventoryButton;  
} 
 
public void addInventoryButtonListener(ActionListener listener) {   
    inventoryButton.addActionListener(listener); 
} 



}
