/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author ASUS
 */
public class Orderhistorypanelreuse extends javax.swing.JPanel {

    /**
     * Creates new form Orderhistorypanelreuse
     */
    public Orderhistorypanelreuse() {
        initComponents();
          this.setPreferredSize(new Dimension(278, 293));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Usernamefield = new javax.swing.JLabel();
        Orderidfield = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderdetailtable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Status = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Username : ");
        add(jLabel1);
        jLabel1.setBounds(20, 6, 90, 18);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Order ID : ");
        add(jLabel2);
        jLabel2.setBounds(20, 40, 100, 24);

        Usernamefield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        add(Usernamefield);
        Usernamefield.setBounds(116, 6, 130, 20);

        Orderidfield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        add(Orderidfield);
        Orderidfield.setBounds(110, 40, 110, 24);

        orderdetailtable.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        orderdetailtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(orderdetailtable);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 83, 264, 160);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Status.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Status.setForeground(new java.awt.Color(255, 255, 255));
        Status.setText("pending");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(Status)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(Status))
        );

        add(jPanel1);
        jPanel1.setBounds(80, 250, 100, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Orderidfield;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Usernamefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderdetailtable;
    // End of variables declaration//GEN-END:variables
public JLabel getUsername(){
    return Usernamefield;
}
public JLabel getorderid(){
    return Orderidfield;
}
public JTable getordertable(){
    return orderdetailtable;
}
public JLabel getstatus(){
    return Status;
}

}
