/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;
/**
 *
 * @author ASUS
 */
public class reusemenupanel extends javax.swing.JPanel {

    /**
     * Creates new form reusemenupanel
     */
    public reusemenupanel() {
        initComponents();
    }
     public void setItemName(String name) {
    nameofitem.setText(name);
}
        public void setItemprice(Double price){
            priceofitem.setText(String.valueOf(price));
        }
        

public void setItemImage(byte[] imageBytes) {
    if (imageBytes == null) return;
    try {
        BufferedImage img = ImageIO.read(new ByteArrayInputStream(imageBytes));
        ImageIcon icon = new ImageIcon(img.getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        forimage.setIcon(icon);
    } catch (Exception e) {
       System.out.println(e);
    }
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameofitem = new javax.swing.JLabel();
        pricename = new javax.swing.JLabel();
        priceofitem = new javax.swing.JLabel();
        forimage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(100, 200));
        setPreferredSize(new java.awt.Dimension(164, 308));

        nameofitem.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        nameofitem.setText("jLabel1");

        pricename.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        pricename.setText("jLabel2");

        priceofitem.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        priceofitem.setText("jLabel3");

        forimage.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(pricename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceofitem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forimage)
                            .addComponent(nameofitem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(forimage)
                .addGap(63, 63, 63)
                .addComponent(nameofitem)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricename)
                    .addComponent(priceofitem))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forimage;
    private javax.swing.JLabel nameofitem;
    private javax.swing.JLabel pricename;
    private javax.swing.JLabel priceofitem;
    // End of variables declaration//GEN-END:variables


}
