/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import model.Employee;

/**
 *
 * @author ASUS
 */
public class WorkerPanelreuse extends javax.swing.JPanel {
private final Employee employee;
    /**
     * Creates new form WorkerPanelreuse
     * @param employee
     */
    public WorkerPanelreuse(Employee employee) {
        this.employee=employee;
        initComponents();
         this.setPreferredSize(new Dimension(1015, 75));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        WorkerID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        Sector = new javax.swing.JLabel();
        Deletebtn = new javax.swing.JButton();
        Editbtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        WorkerID.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        WorkerID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkerID.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.ipady = 59;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(WorkerID, gridBagConstraints);

        Name.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Name.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 18);
        add(Name, gridBagConstraints);

        number.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        number.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(number, gridBagConstraints);

        Sector.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Sector.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sector.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 130;
        add(Sector, gridBagConstraints);

        Deletebtn.setBackground(new java.awt.Color(255, 0, 51));
        Deletebtn.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(Deletebtn, gridBagConstraints);

        Editbtn.setBackground(new java.awt.Color(102, 255, 51));
        Editbtn.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        Editbtn.setText("Edit ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        add(Editbtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Editbtn;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Sector;
    private javax.swing.JLabel WorkerID;
    private javax.swing.JLabel number;
    // End of variables declaration//GEN-END:variables
public JLabel Employednum(){
    return number;
}
public JLabel Namefield(){
    return Name;
}
public JLabel SectorField(){
    return Sector;
}
public JLabel workerid(){
    return WorkerID;
}
public Employee Selectedworker(){
    return employee;
}
public void addEditbtnlistener(ActionListener listener){
    Editbtn.addActionListener(listener);
}
public void adddeletebtnlistener(ActionListener listener){
    Deletebtn.addActionListener(listener);
}


}